### ISSUE TITLE
Game Files

### ISSUE THREAD

**Issue by retro24** [PokeEngineer/NXEngine-RPi#2]
Hello there do i need the original game files eg:Doukutsu.exe  for the pre-build release: nxengine_rpi2_3_4.tar.gz ??

Coz when i run it with ./nx engine it runs the game is it a demo or the full game ??

**Comment by PokeEngineer** [comment]
Hello, sorry for the late response.
The data files are included with the releases, yes.
It is the full freeware version of the game.
